
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useNavigate } from 'react-router-dom';
import { 
  Target, 
  Users, 
  MessageSquare, 
  BarChart3, 
  ArrowRight,
  CheckCircle,
  Zap,
  Shield,
  Globe
} from 'lucide-react';

const HomePage = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: Target,
      title: 'Smart Campaign Creation',
      description: 'AI-powered campaign briefs that resonate with your target audience'
    },
    {
      icon: Users,
      title: 'Creator Discovery',
      description: 'Find the perfect influencers using advanced semantic search'
    },
    {
      icon: MessageSquare,
      title: 'Automated Outreach',
      description: 'Personalized emails and voice messages generated by AI'
    },
    {
      icon: BarChart3,
      title: 'Performance Analytics',
      description: 'Comprehensive reporting and ROI tracking'
    }
  ];

  const benefits = [
    'Reduce campaign setup time by 80%',
    'Increase response rates with personalized outreach',
    'Access to 10M+ creator profiles',
    'AI-powered contract generation',
    'Real-time performance tracking'
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Header */}
      <header className="relative z-10">
        <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-6">
            <div className="flex items-center">
              <h1 className="text-2xl font-bold text-gray-900">InfluencerFlow AI</h1>
            </div>
            <div className="flex items-center space-x-4">
              <Button variant="ghost" onClick={() => navigate('/login')}>
                Sign In
              </Button>
              <Button onClick={() => navigate('/login')}>
                Get Started
              </Button>
            </div>
          </div>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-32">
        <div className="text-center">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Streamline Your{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">
              Influencer Marketing
            </span>
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            From campaign creation to performance reporting, automate your entire influencer marketing workflow with AI-powered tools that save time and drive better results.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              size="lg" 
              className="px-8 py-4 text-lg"
              onClick={() => navigate('/login')}
            >
              Streamline Creator Deals
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
            <Button 
              variant="outline" 
              size="lg" 
              className="px-8 py-4 text-lg"
              onClick={() => window.open('https://youtu.be/-y4WPP7FNCw', '_blank')}
            >
              Watch Demo
            </Button>
          </div>
        </div>

        {/* Hero Image */}
        <div className="mt-20 relative">
          <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-4xl mx-auto">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <Card className="p-6 border-0 bg-gradient-to-br from-blue-50 to-blue-100">
                <CardContent className="p-0">
                  <Target className="h-8 w-8 text-blue-600 mb-4" />
                  <h3 className="font-semibold mb-2">Create Campaign</h3>
                  <p className="text-sm text-gray-600">AI-enhanced briefs</p>
                </CardContent>
              </Card>
              <Card className="p-6 border-0 bg-gradient-to-br from-purple-50 to-purple-100">
                <CardContent className="p-0">
                  <Users className="h-8 w-8 text-purple-600 mb-4" />
                  <h3 className="font-semibold mb-2">Find Creators</h3>
                  <p className="text-sm text-gray-600">Smart matching</p>
                </CardContent>
              </Card>
              <Card className="p-6 border-0 bg-gradient-to-br from-green-50 to-green-100">
                <CardContent className="p-0">
                  <BarChart3 className="h-8 w-8 text-green-600 mb-4" />
                  <h3 className="font-semibold mb-2">Track Results</h3>
                  <p className="text-sm text-gray-600">Real-time analytics</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Everything you need to scale
            </h2>
            <p className="text-xl text-gray-600">
              Powerful features that automate every step of your influencer marketing journey
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="relative overflow-hidden border-0 shadow-lg hover:shadow-xl transition-shadow duration-300">
                <CardContent className="p-8">
                  <div className="absolute top-0 right-0 w-20 h-20 bg-gradient-to-br from-blue-100 to-purple-100 rounded-bl-3xl"></div>
                  <feature.icon className="h-12 w-12 text-blue-600 mb-6 relative z-10" />
                  <h3 className="text-xl font-semibold mb-4">{feature.title}</h3>
                  <p className="text-gray-600">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-4xl font-bold text-gray-900 mb-8">
                Why choose InfluencerFlow AI?
              </h2>
              <div className="space-y-4">
                {benefits.map((benefit, index) => (
                  <div key={index} className="flex items-center">
                    <CheckCircle className="h-6 w-6 text-green-500 mr-4 flex-shrink-0" />
                    <span className="text-lg text-gray-700">{benefit}</span>
                  </div>
                ))}
              </div>
              <Button 
                size="lg" 
                className="mt-8 px-8 py-4"
                onClick={() => navigate('/login')}
              >
                Get Started Today
              </Button>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              <Card className="p-6 border-0 bg-gradient-to-br from-blue-500 to-blue-600 text-white">
                <CardContent className="p-0">
                  <Zap className="h-8 w-8 mb-4" />
                  <h3 className="font-semibold mb-2">10x Faster</h3>
                  <p className="text-blue-100">Campaign setup and execution</p>
                </CardContent>
              </Card>
              <Card className="p-6 border-0 bg-gradient-to-br from-purple-500 to-purple-600 text-white">
                <CardContent className="p-0">
                  <Shield className="h-8 w-8 mb-4" />
                  <h3 className="font-semibold mb-2">Secure</h3>
                  <p className="text-purple-100">Enterprise-grade security</p>
                </CardContent>
              </Card>
              <Card className="p-6 border-0 bg-gradient-to-br from-green-500 to-green-600 text-white sm:col-span-2">
                <CardContent className="p-0">
                  <Globe className="h-8 w-8 mb-4" />
                  <h3 className="font-semibold mb-2">Global Reach</h3>
                  <p className="text-green-100">Access creators worldwide across all major platforms</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-blue-600 to-purple-600">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <h2 className="text-4xl font-bold text-white mb-6">
            Ready to transform your influencer marketing?
          </h2>
          <p className="text-xl text-blue-100 mb-8">
            Join thousands of brands already using InfluencerFlow AI to scale their influence
          </p>
          <Button 
            size="lg" 
            variant="secondary"
            className="px-8 py-4 text-lg"
            onClick={() => navigate('/login')}
          >
            Start Your Free Trial
            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h3 className="text-2xl font-bold mb-4">InfluencerFlow AI</h3>
            <p className="text-gray-400">
              Streamlining influencer marketing with artificial intelligence
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default HomePage;
