// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azyzcriqrredtkovtmat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6eXpjcmlxcnJlZHRrb3Z0bWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzQxMDIsImV4cCI6MjA2NDIxMDEwMn0.ZnaTbL1U54No3a3Xa9rc1Zoy_kyAFahpA0jdeDzymmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);